"""
Tier 1 Ontology Writer

리서치 에이전트가 수집한 Tier 1 데이터를 기존 온톨로지 패턴에 맞는
Python 모듈로 생성. app/ontology/ 디렉토리에 추가 가능한 형태.
"""

import json
from pathlib import Path
from datetime import datetime


class Tier1OntologyWriter:
    """Tier 1 데이터를 Python 온톨로지 모듈로 변환"""

    def __init__(self, output_dir: Path = None):
        self.output_dir = output_dir or Path(__file__).parent.parent.parent / "app" / "ontology"

    def write_foundry_ontology(self, data: dict) -> Path:
        """Foundry/FabSite 데이터를 foundry.py 온톨로지로 변환"""
        foundries = [n for n in data.get("nodes", []) if n.get("label") == "Foundry"]
        fabs = [n for n in data.get("nodes", []) if n.get("label") == "FabSite"]

        code = self._generate_header("Foundry & Fab Site Ontology",
                                     "파운드리 기업 및 전세계 팹 사이트 정보")
        code += self._generate_imports()

        # Foundry dataclass
        code += """

@dataclass
class FoundrySpec:
    \"\"\"파운드리 기업 사양\"\"\"
    name: str
    full_name: str
    country: str
    hq: str
    founded_year: int
    fab_count: int
    revenue_b_usd: float
    market_share_pct: float
    description: str


@dataclass
class FabSiteSpec:
    \"\"\"팹 사이트 사양\"\"\"
    name: str
    foundry_key: str
    location: str
    wafer_size_mm: int
    capacity_wspm: int
    status: str
    process_nodes: list[str]
    opened_year: Optional[int] = None
    investment_b_usd: Optional[float] = None
    description: str = ""

"""
        # Foundry 데이터
        code += "FOUNDRIES: dict[str, FoundrySpec] = {\n"
        for f in foundries:
            props = f.get("properties", {})
            code += f'    "{f["key"]}": FoundrySpec(\n'
            code += f'        name="{f["name"]}",\n'
            code += f'        full_name="{props.get("full_name", f["name"])}",\n'
            code += f'        country="{props.get("country", "")}",\n'
            code += f'        hq="{props.get("hq", "")}",\n'
            code += f'        founded_year={props.get("founded_year", 0)},\n'
            code += f'        fab_count={props.get("fab_count", 0)},\n'
            code += f'        revenue_b_usd={props.get("revenue_b_usd", 0)},\n'
            code += f'        market_share_pct={props.get("market_share_pct", 0)},\n'
            code += f'        description="{props.get("description", "")}",\n'
            code += '    ),\n'
        code += "}\n\n"

        # FabSite 데이터
        code += "FAB_SITES: dict[str, FabSiteSpec] = {\n"
        for f in fabs:
            props = f.get("properties", {})
            pn_list = props.get("process_nodes", [])
            code += f'    "{f["key"]}": FabSiteSpec(\n'
            code += f'        name="{f["name"]}",\n'
            code += f'        foundry_key="{props.get("foundry_key", "")}",\n'
            code += f'        location="{props.get("location", "")}",\n'
            code += f'        wafer_size_mm={props.get("wafer_size_mm", 300)},\n'
            code += f'        capacity_wspm={props.get("capacity_wspm", 0)},\n'
            code += f'        status="{props.get("status", "ACTIVE")}",\n'
            code += f'        process_nodes={json.dumps(pn_list)},\n'
            code += f'        opened_year={props.get("opened_year", "None")},\n'
            code += f'        investment_b_usd={props.get("investment_b_usd", "None")},\n'
            code += f'        description="{props.get("description", "")}",\n'
            code += '    ),\n'
        code += "}\n\n"

        # Lookup interface
        code += """
class FoundryOntology:
    \"\"\"파운드리 도메인 온톨로지 인터페이스\"\"\"

    @staticmethod
    def get_all_foundries() -> dict[str, FoundrySpec]:
        return FOUNDRIES

    @staticmethod
    def get_foundry(key: str) -> Optional[FoundrySpec]:
        return FOUNDRIES.get(key)

    @staticmethod
    def get_all_fab_sites() -> dict[str, FabSiteSpec]:
        return FAB_SITES

    @staticmethod
    def get_fab_sites_by_foundry(foundry_key: str) -> list[FabSiteSpec]:
        return [f for f in FAB_SITES.values() if f.foundry_key == foundry_key]
"""

        output_file = self.output_dir / "foundry.py"
        output_file.write_text(code, encoding="utf-8")
        return output_file

    def write_all(self, data: dict) -> list[Path]:
        """모든 Tier 1 온톨로지 생성"""
        files = []
        files.append(self.write_foundry_ontology(data))
        return files

    def _generate_header(self, title: str, description: str) -> str:
        return f'"""\n{title}\n\n{description}\n\nAuto-generated by Research Agent at {datetime.utcnow().isoformat()}\n"""\n'

    def _generate_imports(self) -> str:
        return "from dataclasses import dataclass, field\nfrom typing import Optional\n"
