// Auto-generated by Research Agent
// Execute in Neo4j Browser

MERGE (n:DesignIP {key: 'ARM_HOLDINGS'})
ON CREATE SET n.key = 'ARM_HOLDINGS', n.name = 'ARM Holdings', n.vendor = 'ARM Holdings', n.type = 'CPU IP Licensing', n.architecture = 'ARM', n.location = 'Cambridge, England', n.business_model = 'IP licensing', n.market_position = 'dominant in mobile processors', n.ownership = 'majority owned by SoftBank Group since 2016', n.valuation_2023 = '54.5 billion USD', n.chips_produced = 'over 230 billion', n.confidence = 0.85, n.source_date = '2023', n.freshness_score = 0.7, n._quality_scored_at = '2026-02-01T05:39:19.506003';

MERGE (n:DesignIP {key: 'ARM_MALI_GPU'})
ON CREATE SET n.key = 'ARM_MALI_GPU', n.name = 'ARM Mali GPU', n.vendor = 'ARM Holdings', n.type = 'GPU IP', n.architecture = 'Mali', n.target_application = 'mobile graphics', n.confidence = 0.85, n.source_date = '2025', n.freshness_score = 0.95, n._quality_scored_at = '2026-02-01T05:39:19.506014';

MERGE (n:DesignIP {key: 'ARM_IMMORTALIS_GPU'})
ON CREATE SET n.key = 'ARM_IMMORTALIS_GPU', n.name = 'ARM Immortalis GPU', n.vendor = 'ARM Holdings', n.type = 'GPU IP', n.architecture = 'Immortalis', n.features = 'hardware-based ray-tracing', n.target_application = 'premium mobile graphics', n.confidence = 0.85, n.source_date = '2025', n.freshness_score = 0.95, n._quality_scored_at = '2026-02-01T05:39:19.506019';

MERGE (n:DesignIP {key: 'RISCV_ISA'})
ON CREATE SET n.key = 'RISCV_ISA', n.name = 'RISC-V ISA', n.vendor = 'RISC-V International', n.type = 'Open ISA', n.architecture = 'RISC-V', n.licensing = 'open-source, royalty-free', n.developed_year = '2010', n.location = 'University of California, Berkeley (origin)', n.organization_location = 'Switzerland', n.members = 'over 4500 as of 2025', n.target_application = 'microcontrollers, embedded systems, mobile, desktop, server', n.confidence = 0.85, n.source_date = '2025', n.freshness_score = 0.95, n._quality_scored_at = '2026-02-01T05:39:19.506024';

MERGE (n:DesignIP {key: 'SYNOPSYS_EDA'})
ON CREATE SET n.key = 'SYNOPSYS_EDA', n.name = 'Synopsys EDA Tools', n.vendor = 'Synopsys', n.type = 'EDA Tools', n.location = 'Sunnyvale, California', n.market_position = 'leading EDA vendor', n.products = 'digital and analog circuit implementation, simulators, debugging environments', n.ranking_2024 = '12th largest software company worldwide', n.confidence = 0.85, n.source_date = '2024', n.freshness_score = 0.75, n._quality_scored_at = '2026-02-01T05:39:19.506031';

MERGE (n:DesignIP {key: 'CADENCE_EDA'})
ON CREATE SET n.key = 'CADENCE_EDA', n.name = 'Cadence EDA Tools', n.vendor = 'Cadence Design Systems', n.type = 'EDA Tools', n.location = 'San Jose, California', n.products = 'IC design, SoC design, PCB design, IP licensing', n.target_application = 'electronics, aerospace, defense, automotive', n.confidence = 0.85, n.source_date = '2025', n.freshness_score = 0.95, n._quality_scored_at = '2026-02-01T05:39:19.506035';

MERGE (n:DesignIP {key: 'SIFIVE_RISCV'})
ON CREATE SET n.key = 'SIFIVE_RISCV', n.name = 'SiFive RISC-V Cores', n.vendor = 'SiFive', n.type = 'CPU IP', n.architecture = 'RISC-V', n.target_application = 'commercial SoCs', n.confidence = 0.85, n.source_date = '2025', n.freshness_score = 0.95, n._quality_scored_at = '2026-02-01T05:39:19.506040';

MERGE (n:DesignIP {key: 'ANDES_RISCV'})
ON CREATE SET n.key = 'ANDES_RISCV', n.name = 'Andes RISC-V Cores', n.vendor = 'Andes Technology', n.type = 'CPU IP', n.architecture = 'RISC-V', n.target_application = 'commercial SoCs', n.confidence = 0.85, n.source_date = '2025', n.freshness_score = 0.95, n._quality_scored_at = '2026-02-01T05:39:19.506061';

MERGE (n:DesignIP {key: 'STARFIVE_RISCV'})
ON CREATE SET n.key = 'STARFIVE_RISCV', n.name = 'StarFive RISC-V Cores', n.vendor = 'StarFive', n.type = 'CPU IP', n.architecture = 'RISC-V', n.target_application = 'commercial SoCs', n.confidence = 0.85, n.source_date = '2025', n.freshness_score = 0.95, n._quality_scored_at = '2026-02-01T05:39:19.506067';

MERGE (n:DesignIP {key: 'ESPRESSIF_RISCV'})
ON CREATE SET n.key = 'ESPRESSIF_RISCV', n.name = 'Espressif RISC-V MCUs', n.vendor = 'Espressif Systems', n.type = 'MCU IP', n.architecture = 'RISC-V', n.target_application = 'microcontrollers', n.confidence = 0.85, n.source_date = '2025', n.freshness_score = 0.95, n._quality_scored_at = '2026-02-01T05:39:19.506072';

MATCH (a {key: 'ARM_HOLDINGS'}), (b {key: 'ARM_MALI_GPU'}) MERGE (a)-[:USES_IP]->(b);
MATCH (a {key: 'ARM_HOLDINGS'}), (b {key: 'ARM_IMMORTALIS_GPU'}) MERGE (a)-[:USES_IP]->(b);
MATCH (a {key: 'SIFIVE_RISCV'}), (b {key: 'RISCV_ISA'}) MERGE (a)-[:USES_IP]->(b);
MATCH (a {key: 'ANDES_RISCV'}), (b {key: 'RISCV_ISA'}) MERGE (a)-[:USES_IP]->(b);
MATCH (a {key: 'STARFIVE_RISCV'}), (b {key: 'RISCV_ISA'}) MERGE (a)-[:USES_IP]->(b);
MATCH (a {key: 'ESPRESSIF_RISCV'}), (b {key: 'RISCV_ISA'}) MERGE (a)-[:USES_IP]->(b);
MATCH (a {key: 'SYNOPSYS_EDA'}), (b {key: 'N3E'}) MERGE (a)-[:USES_IP]->(b);
MATCH (a {key: 'CADENCE_EDA'}), (b {key: 'N3E'}) MERGE (a)-[:USES_IP]->(b);
MATCH (a {key: 'SYNOPSYS_EDA'}), (b {key: 'N5'}) MERGE (a)-[:USES_IP]->(b);
MATCH (a {key: 'CADENCE_EDA'}), (b {key: 'N5'}) MERGE (a)-[:USES_IP]->(b);